pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginStatusProvider.java, pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginStatusProviderTest.java
=> Added Test for PluginStatusProvider

pf4j/src/main/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinder.java, pf4j/src/main/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinder.java
@tuxedo0801 What you think? I heave a little problem in Test class but I will fix it.
With this PR I think that you have an elegant and very flexible scheme to override some behaviors of the `PluginDescriptorFinder` implementations and to fix #70.
=> improve PluginDescriptorFinder implementations (see #70)

demo_gradle/app/build.gradle, demo_gradle/plugins/plugin1/build.gradle, demo_gradle/plugins/plugin2/build.gradle
Fix for issue #103 and added the SLF4J simple to the gradle demo's app project
=> Fix for issue #103 and added the SLF4 Simple dependency

pf4j/src/main/java/ro/fortsoft/pf4j/Extension.java
Hi @decebals, here a small update for inheritance support on extension model. No need for AnnotationProcessor changes. Works well in my project.
=> Add inheritance support on Extension annot

demo_gradle/.gitignore, demo_gradle/api/build.gradle, demo_gradle/app/build.gradle, demo_gradle/build.gradle, demo_gradle/plugins/plugin1/build.gradle, demo_gradle/plugins/plugin2/build.gradle
Fixed compilation errors after update.
Added copyPlugins task to gradle which copies all generated plugin.zip's to the app/plugins directory.
=> Updated pf4j to newest version.

demo_gradle/plugins/plugin1/build.gradle, demo_gradle/plugins/plugin2/build.gradle
Fixed issue: #123 
Same as: https://github.com/decebals/pf4j/blob/master/demo/api/pom.xml#L32
=> Added compileOnly to "api" dependencies in plugins.

pf4j/src/main/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinder.java, pf4j/src/test/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinderTest.java
Adding parsing of plugin.description and plugin.requires to the properties finder, and added a test
=> Properties Descriptor finder bug fixes and a test

pf4j/src/main/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinder.java, pf4j/src/main/java/ro/fortsoft/pf4j/PluginDescriptor.java, pf4j/src/main/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinder.java, pf4j/src/test/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinderTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinderTest.java
e.g. Apache-2.0 or MIT
Also adds missing vars `description` and `requires` to toString
=> Support for adding license information to the plugins

CHANGELOG.md, pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java, pf4j/src/main/java/ro/fortsoft/pf4j/PluginDescriptor.java, pf4j/src/test/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinderTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinderTest.java
=> Refactor of requires in PluginDescriptor (breaking change)

pf4j/pom.xml, pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java, pf4j/src/main/java/ro/fortsoft/pf4j/util/FileUtils.java, pf4j/src/test/java/ro/fortsoft/pf4j/LoadPluginsTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/plugin/MockPluginManager.java, pf4j/src/test/java/ro/fortsoft/pf4j/util/FileUtilsTest.java
Also:
Test-logging using log4j
Bugfix for expandIfZip - would fail on new folders without "." in the name
Bugfix for duplicate check (pathToIdMap)
The new test should give a huge bump in test coverage :-)
=> New LoadPluginsTest

README.md, pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java, pf4j/src/main/java/ro/fortsoft/pf4j/PluginDescriptor.java, pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginManagerTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinderTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinderTest.java, pf4j/src/test/java/ro/fortsoft/pf4j/util/SemVerUtils.java
* Introduce config flag exactVersionAllowed to interpret exact versions as >= expression
* Moves Expression parsing and validation from PluginDescriptor to PluginManager
* Added tests
=> Refactor requires validation, Fixes #142

demo_gradle/README.md, demo_gradle/api/build.gradle, demo_gradle/app/build.gradle, demo_gradle/app/src/main/java/org/pf4j/demo/Boot.java, demo_gradle/build.gradle, demo_gradle/gradle.properties, demo_gradle/plugins/build.gradle, demo_gradle/plugins/plugin1/build.gradle, demo_gradle/plugins/plugin1/gradle.properties, demo_gradle/plugins/plugin1/plugin.properties, demo_gradle/plugins/plugin2/build.gradle, demo_gradle/plugins/plugin2/gradle.properties, demo_gradle/plugins/plugin2/plugin.properties, demo_gradle/plugins/plugin3/build.gradle, demo_gradle/plugins/plugin3/gradle.properties, demo_gradle/settings.gradle
* Fixed Gradle demo
* Updated PF4J version for the demo
* Added a README that explains the demo
=> ISSUE-169: fix gradle demo

demo/app/src/main/java/org/pf4j/demo/Boot.java, pf4j/src/main/java/org/pf4j/AbstractPluginManager.java, pf4j/src/main/java/org/pf4j/PluginManager.java
Implements https://github.com/decebals/pf4j/issues/190
=> Can now just get Extension classes

pf4j/src/main/java/org/pf4j/DevelopmentPluginClasspath.java, pf4j/src/main/java/org/pf4j/PluginClasspath.java
I tried to improve `DevelopmentPluginClasspath` using the ideas/feedback from #195.
=> Improve DevelopmentPluginClasspath according #195

pf4j/src/main/java/org/pf4j/DefaultPluginRepository.java, pf4j/src/test/java/org/pf4j/DefaultPluginRepositoryTest.java
Added additional filter for "build" folder which is the default output folder for Gradle projects.
=> Improving development mode experience for Gradle users #195

pf4j/src/test/java/org/pf4j/LegacyExtensionFinderTest.java
Recreates FileSystemException in windows on plugin delete
=> Recreate file system windows exception

pf4j/src/main/java/org/pf4j/PluginState.java
This will help handling all cases and new values (if it ever happens) by using switch statements at least. See issue #326
=> Modified org.pf4j.PluginState to an enum

pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java
I think you meant to check `result` here, instead of `entries` :-)
=> Check proper list for debug logging

pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java
Improve annotation processor error messages for #369.
=> Improve annotation processor error messages

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java, pf4j/src/main/java/org/pf4j/PluginManager.java, pf4j/src/test/java/org/pf4j/JarPluginManagerTest.java
One more update to fix test execution on Windows.
BTW, when do you planning to release next version?
=> Fix for problem with file lock on Windows platform. Introduce unloadPlugins method.

pf4j/src/main/java/org/pf4j/DependencyResolver.java
=> added toString to WrongDependencyVersion to solve issue #396

pom.xml
=> update mockito version from 2.24.0 to 3.8.0

pf4j/src/test/java/org/pf4j/SingletonExtensionFactoryTest.java
=> fix the path separator used in the SingletonExtensionFactoryTest.java

pf4j/src/main/java/org/pf4j/DefaultVersionManager.java, pf4j/src/test/java/org/pf4j/DefaultVersionManagerTest.java
=> fixed Dependency version check fails even if required is *

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java, pf4j/src/test/java/org/pf4j/JarPluginManagerTest.java
The problem is described in #546
=> unload broken plugins fix

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java, pf4j/src/main/java/org/pf4j/PluginState.java, pf4j/src/test/java/org/pf4j/DefaultPluginManagerTest.java
=> Post `PluginState.UNLOADED` event when plugins are unloaded

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java, pf4j/src/test/java/org/pf4j/DefaultPluginManagerTest.java
Closes https://github.com/pf4j/pf4j/issues/574
The problem might be introduced in <https://github.com/pf4j/pf4j/commit/30f415fe2d92d38ab84cac119e52fd54a4bc36ba>.
=> Fix the problem of not being able to disable plugins correctly

pf4j/src/main/java/org/pf4j/PluginClassLoader.java, pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java
Always look for the EXTENSIONS_RESOURCE in PluginClassLoader first (PDA strategy)
=> Plugin Extensions should be detected with any ClassLoadingStrategy

README.md
The previous README link 404'd.
=> Update WhazzupGreeting link
