pf4j/pf4j

pf4j/src/main/java/ro/fortsoft/pf4j/ServiceProviderExtensionFinder.java

Replace working with content of plugin jars with NIO.
new File(url.toURI()) -> FileSystems.newFileSystem(url.toURI() ...

Fix issue "URI is not hierarchical" when working with extensions jar's

---

pf4j/src/main/java/ro/fortsoft/pf4j/PluginClassLoader.java
pf4j/src/main/java/ro/fortsoft/pf4j/ServiceProviderExtensionFinder.java

Pull request #87 fixed this problem for `readClasspathStorages()` but not for `readPluginsStorages()`. This applies the same fix.

Fix "URI is not hierarchical" issue

---

demo/app/src/main/java/ro/fortsoft/pf4j/demo/Boot.java
pf4j/src/main/java/ro/fortsoft/pf4j/AbstractExtensionFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultExtensionFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/ExtensionFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/ExtensionWrapper.java
pf4j/src/main/java/ro/fortsoft/pf4j/LegacyExtensionFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/ServiceProviderExtensionFinder.java

In few words, this PR add below methods in `PluginManager`:
- `<T> List<T> getExtensions(Class<T> type, String pluginId)`
- `List getExtensions(String pluginId)`
See more details about these methods on https://groups.google.com/forum/#!topic/pf4j/vqnD1abLXjA.

Return a list of all extensions from a plugin and optional for an ension point

---

demo/app/src/main/java/ro/fortsoft/pf4j/demo/Boot.java
pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/BasePluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/CompoundPluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginClasspath.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginDescriptorFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginFactory.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginLoader.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginStatusProvider.java
pf4j/src/main/java/ro/fortsoft/pf4j/DependencyResolver.java
pf4j/src/main/java/ro/fortsoft/pf4j/DevelopmentPluginClasspath.java
pf4j/src/main/java/ro/fortsoft/pf4j/JarPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginClassLoader.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginClasspath.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginDescriptorFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginLoader.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginWrapper.java
pf4j/src/main/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinder.java
pf4j/src/main/java/ro/fortsoft/pf4j/util/FileUtils.java
pf4j/src/main/java/ro/fortsoft/pf4j/util/Unzip.java
pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginRepositoryTest.java
pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginStatusProviderTest.java
pf4j/src/test/java/ro/fortsoft/pf4j/ManifestPluginDescriptorFinderTest.java
pf4j/src/test/resources/log4j.properties

This PR comes with many good things.
First of all, it comes with a builtin `JarPluginManager` (see #118). According javadoc:
>  It's a {@link PluginManager} that load plugin from a jar file.
> Actually, a plugin is a fat jar, a jar which contains classes from all the libraries,
> on which your project depends and, of course, the classes of current project.
So, your plugins are jar files that could be created using [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin).
To add the possibility to create custom `PluginManager` more easy, this PR introduces new concepts:
- AbstractPluginManager
- PluginLoader
The current implementation of `JarPluginManager` is:
```java
public class JarPluginManager extends DefaultPluginManager {
@Override
protected PluginRepository …
```

Add JarPluginManager, PluginLoader, AbstractPluginManager

---

pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java

I have a custom PluginManager, and when the `getVersion()` code attempts to log PF4J's version in initialize(), it uses `getClass()` to fetch implementationVersion. This assumes that getClass returns a PF4J class, but it returns my own class, which incidentially has a version not parsable by semVer Version class (it contains a space and git hash after the version string).
The fix is to always use a pf4j class for calculating the version.

getVersion() use wrong class for calculating PF4J version

---

pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/BasePluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/util/FileUtils.java
pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginRepositoryTest.java

`deletePlugin(id)` which is called by `UpdateManager.uninstallPlugin(id)` failed since the `PluginRepository.deletePluginPath()` call used `Files.deleteIfExists(path)` which is not able to delete recursively.
The fix is to use the already existing `FileUtils.delete(path)`, which I modified to `java.nio` style and no follow symlinks.

deletePlugin() failed to delete plugin folder with contents

---

pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/util/FileUtils.java
pf4j/src/test/java/ro/fortsoft/pf4j/DefaultPluginRepositoryTest.java

Delete plugin zip file from `pluginsRoot` as part of `deletePlugin(id)`

Delete plugin zip on uninstall

---

pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/PluginDescriptor.java
pf4j/src/test/java/ro/fortsoft/pf4j/PropertiesPluginDescriptorFinderTest.java

Instead we get the className. As I could not find any method on Expression to convert back to String, this fix adds a `requiresString` variable to PluginInfo.

The requires Expression does not print well

---

pf4j/src/main/java/ro/fortsoft/pf4j/PluginManager.java

Simple fix which will make https://github.com/decebals/pf4j-update/pull/11 more elegant

Ability to get pluginsRoot from PluginManager

---

pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginManager.java
pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginRepository.java
pf4j/src/main/java/ro/fortsoft/pf4j/util/FileUtils.java
pf4j/src/test/java/ro/fortsoft/pf4j/util/FileUtilsTest.java

This is an attempt for auto unzip on load, so UpdateManager can install and update without problems. Was this the approach you had in mind?
Fixes #132

Unzip plugin zip file in loadPluginFromPath()

---

demo_gradle/api/build.gradle
demo_gradle/app/build.gradle
demo_gradle/app/src/main/java/ro/fortsoft/pf4j/demo/Boot.java
demo_gradle/plugins/plugin1/build.gradle
demo_gradle/plugins/plugin1/src/main/java/ro/fortsoft/pf4j/demo/welcome/WelcomePlugin.java
demo_gradle/plugins/plugin2/build.gradle
demo_gradle/plugins/plugin2/src/main/java/ro/fortsoft/pf4j/demo/hello/HelloPlugin.java
demo_gradle/plugins/plugin3/build.gradle
demo_gradle/plugins/plugin3/src/main/kotlin/ro/fortsoft/pf4j/demo/kotlin/KotlinPlugin.kt

Updated pf4j and commons gradle dependencies to newest version and changed all build settings so we can use slf4j in plugins#148 
we needed to exclude all slf4j libraries from all plugins to get them to work.

Updated gradle demo dependencies and switched from S.out.println to slf4j

---

pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java
pf4j/src/main/java/org/pf4j/ExtensionDescriptor.java
pf4j/src/main/java/org/pf4j/ExtensionWrapper.java

`ExtensionWrapper` and `ExtensionDescriptor` have poor public API which doesn't allow using them outside of `org.pf4j` package, but these classes are parts of public API of pf4j library.
This change converts `ExtensionDescriptor` to be an immutable object with all public fields that cannot be changed after creation. Also, removed `setExtensionFactory` from `ExtensionWrapper` in favor of a constructor parameter.

Improve public API of Extention* classes

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java

The framework can properly function without plugins root by loading plugins from classpath so there is no reason to log an error, warning should be enough.

Emit warning instead of error when plugin root is not present

---

pf4j/src/main/java/org/pf4j/DefaultPluginManager.java

when subclassing `DefaultPluginManager` you are forced to create a `CompoundPluginDescriptorFinder` even if you only need one

@Override should not change method signature

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/ManifestPluginDescriptorFinder.java

According to the [Plugin lifecycle](https://github.com/decebals/pf4j#plugin-lifecycle), a plugin stopped should be able to be removed. But it couldn't. Threre still is some stream opened.
One is in the PluginDescriptor, the other is the URLClassLoader.

close JarFile stream after getManifest

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java

Removed unnecessary call to set pf4j.pluginsDir if plugin root is set via the constructor.

Fixes #206

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/PluginManager.java

What the title says. Was looking for that method in the API but I didn't see it, was there a particular reason why is it missing?
In any case, it'd work exactly the same as the other methods since the default finder is already capable of doing it.
I am partial to creating an array and returning with Arrays.asList instead of creating a new ArrayList (since as an object it's a bit more compact, or just returning an array is viable too), but that'd be a different behavior from the rest of the methods.

Allow a way to query all extension classes for a given plugin

---

pf4j/src/main/java/org/pf4j/LegacyExtensionFinder.java
pf4j/src/main/java/org/pf4j/ServiceProviderExtensionFinder.java

The extension finder does not take plugin libraries (in the plugin's `lib` directory) into consideration. 
This pull request updates the `LegacyExtensionFinder` / `ServiceProviderExtensionFinder` class in order to scan the plugin libraries for `META-INF/extensions.idx` / `META-INF/services`.

load extensions from plugin libraries

---

pf4j/src/main/java/org/pf4j/Extension.java
pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java
pf4j/src/main/java/org/pf4j/util/ClassUtils.java

This pull requests provides a possible workaround for issue #264.
An extension may provide its implemented extension points explicitly through its annotation. According to my example in issue #264 you might use:
```java
@Extension(provides = {BootExtensionPoint.class})
public class Plugin1BootExtension extends BootAdapter {
// ... some implementations 
}
```
If the `@Extension` provides its implemented extension points through the `provides` attribute, there is no need for the annotation processor to detect the extension points automatically, which currently fails under the described conditions.
I know, that this might not the best approach. I guess you also can improve the automatic detection of extension points in the [`findExtensionPoints`](https://github.com/pf4j/pf4j/blob/ab12f7fa5a95 …

explicitly configure extension points for an extension

---

pf4j/src/main/java/org/pf4j/LegacyExtensionFinder.java
pf4j/src/main/java/org/pf4j/ServiceProviderExtensionFinder.java

This pull request fixes issue #272.
Similar to the implementation in [`LegacyExtensionFinder#readClasspathStorages()`](https://github.com/pf4j/pf4j/blob/39219b3ba4a8bc7c13e6ede8d7157518e266bba1/pf4j/src/main/java/org/pf4j/LegacyExtensionFinder.java#L49-L66) the `ServiceProviderExtensionFinder` should also iterate over all available `META-INF/services` directories (see [this commit](https://github.com/pf4j/pf4j/pull/273/commits/0f715f09e871d1920b891f53cded2c9562198d9c)).
Besides this I made a little change to `LegacyExtensionFinder#readClasspathStorages()` in order to have a more consistent logging (see [this commit](https://github.com/pf4j/pf4j/pull/273/commits/d1500cd4c466cd9e16ae8710c6e6f82012edaffb)).

ServiceProviderExtensionFinder should scan the whole classpath

---

pf4j/pom.xml

According to [this recommendation](http://branchandbound.net/blog/java/2017/12/automatic-module-name/) the `pf4j.jar` file should provide an `Automatic-Module-Name` in its `MANIFEST.MF`. This pull requests extends the `pom.xml` in order to add the line 
```
Automatic-Module-Name: org.pf4j
```
to the `MANIFEST.MF` of `pf4j.jar` (see [this commit](https://github.com/pf4j/pf4j/pull/275/commits/992aa3012de64e6b002a07ead034b76ef90cc878)). In case PF4J is migrated to Jigsaw (Java 9+) in the future, you can use `org.pf4j` in the `module-info.java` without getting conflicts with application, that already make use of Jigsaw (Java 9+).
I didn't make any changes to the demo application. Because in most cases the demo libraries aren't reused by other applications.

add automatic module name to pf4j.jar

---

demo/plugins/pom.xml

I tried running `run-demo.sh` and found that the results were not correct: WelcomePlugin and HelloPlugin could be loaded, but the extensions didn't work. 
The log message:
```
Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
>>> Whazzup
WelcomePlugin.start()
HelloPlugin.start()
HelloPlugin.stop()
WelcomePlugin.stop()
```
I found it was due to a modification of a commit: https://github.com/pf4j/pf4j/commit/254c9cc9ebb6743c5fa526044a67e2aaa0101b7c
The log after the repair is:
```
Found 3 extensions for extension point 'org.pf4j.demo.api.Greeting'
>>> Whazzup
>>> Welcome
>>> Hello
WelcomePlugin.start()
HelloPlugin.start()
HelloPlugin.stop()
WelcomePlugin.stop()
```
Thanks.

Fix the plugins in the demo did not load successfully

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/DependencyResolver.java
pf4j/src/main/java/org/pf4j/PluginManager.java
pf4j/src/main/java/org/pf4j/PluginStatusProvider.java

Document that `pluginId` comes from the plugin metadata. The metadata
currently can be specified in either JAR manifest as "Plugin-Id" or in a property file as "plugin.id".

Document where the pluginId comes from

---

.travis.yml
demo/app/pom.xml
demo/plugins/pom.xml
pom.xml

Update dependencies to enable build on Java 11:
- Update Mockito and plugins for 11 support.
- Disable doclint as there are numerous Javadoc issues reported.
- Remove jdk8-build profile, as 'additionalparam' property isn't
used in POM.
- Disable Javadoc generation on 11+, as it currently fails.
Add travis build on OpenJDK11.

Make the project build on Java 11

---

pf4j/pom.xml
pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/test/java/org/pf4j/LoadPluginsTest.java
pom.xml

Check no plugin with same pluginId is loaded before loading a new plugin.
Also, update Hamcrest to [2.1](https://github.com/hamcrest/JavaHamcrest/releases/tag/v2.1).
Fixes #286

Check no plugin with same pluginId is loaded

---

pom.xml

The asm library was recently updated to version 7.1. It is backwards compatible only contains bugfixes (see [changelog](https://asm.ow2.io/versions.html#7.1)). This pull requests updates the dependency version in PF4J accordingly.

update asm library to version 7.1

---

pf4j/pom.xml
pf4j/src/main/java/module-info.java
pom.xml

This pull request addresses issue #299.
A `module-info.java` file was created. It defines the following requirements:
- [`java.base`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/module-summary.html) is always required. We don't really need to define this, but I like to set this for the sake of completeness.
- [`java.compiler`](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/module-summary.html) is required for annotation processing.
- `org.objectweb.asm` is provided by the ASM library.
- `slf4j.api` is automatically named, because the library does not provide its own module name. Version 1.8 defines a module called `org.slf4j`. But this version is currently in beta stage. Therefore I'm not sure, if we already like to use it.
- `java.semver` is …

Provide a module descriptor for Java 9+

---

demo/api/pom.xml
demo/app/pom.xml
demo/plugins/plugin1/pom.xml
demo/plugins/plugin2/pom.xml
demo/plugins/pom.xml
demo/pom.xml
pf4j/pom.xml
pom.xml

For a better distinction between the different development branches, I would suggest to update the version numbers in the `pf4j_3` branch to `3.0.0-SNAPSHOT`.

set version number to 3.0.0-SNAPSHOT

---

demo/plugins/pom.xml

Because Java 8 is required with PF4J 3, it doesn't really make sense to compile the demo plugins for Java 7. Therefore I've updated the `pom.xml` accordingly.
In general I'm not sure, if we really need this setting anyway. Do you have any reason for providing the target Java version here again? - If we would remove this setting, it would be automatically inherited from the the root `pom.xml`, where `<maven.compiler.release>8</maven.compiler.release>` is already configured.

compile demo plugins for Java 8

---

pf4j/pom.xml

During some tests with PF4J 3 I've discovered a problem related to Java modules. I've converted the demo application to Java 11 modules. It uses a similar structure, a developer would use for a new project based on PF4J & Java 11.
Compiling this project with Java 11 leads to an error message. The compiler does not find the `module-info.class` introduced with #300. In the current state the module is not usable, because it is placed in the `META-INF/versions/9` folder of the JAR file. In this case we need to add the line `Multi-Release: true` to the manifest of pf4j.jar as described [here](https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html#The_.22forward_compatibility.22_solution) and [here](https://dzone.com/articles/creating-multi-release-jar-files-in-intellij-idea). …

add "Multi-Release" to manifest

---

pf4j/src/main/java/org/pf4j/PluginWrapper.java

I'm currently faced with the problem that my custom plugin manager is unable to set the plugin factory and state since the methods are not public. The only way how I can manage this is to move my manager to the `org.pf4j` package.
My manager provides this method to quickly deploy plugins without the need to load them from filesystem:
```java
private PluginWrapper loadPlugin(Class<?> clazz, String pluginId) {
MeshPluginDescriptor pluginDescriptor = new MeshPluginDescriptorImpl(pluginId, clazz);
log.debug("Found descriptor {}", pluginDescriptor);
String pluginClassName = clazz.getName();
log.debug("Class '{}' for plugin", pluginClassName);
// create the plugin wrapper
log.debug("Creating wrapper for plugin '{}'", pluginClassName);
PluginWrapper pluginWrapper = new PluginWrapper(this, …
```

Make PluginWrapper methods public

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java

This will allow custom plugin managers to add custom setters for pluginsRoot. This way the pluginsRoot can be re-configured during runtime.

Make AbstractPluginManager fields protected

---

pf4j/src/main/java/org/pf4j/DevelopmentPluginClasspath.java

According to [IDEA help](https://www.jetbrains.com/help/idea/specifying-compilation-settings.html), add default IDEA classpath in case developing in IDEA.
For reference, IDEA classpath setting should be changed as [here](https://stackoverflow.com/questions/13799061)

Add IDEA classpath for Development mode

---

pf4j/src/main/java/org/pf4j/DefaultPluginDescriptor.java
pf4j/src/main/java/org/pf4j/PluginClasspath.java
pf4j/src/main/java/org/pf4j/PluginDependency.java
pf4j/src/test/java/org/pf4j/PluginDependencyTest.java

We have extended DefaultPluginDescriptor to add some extra attributes
and not having equals/hashCode implemented makes it a bit tough to
write good tests around our PluginDescriptorFinder implementation.
This just adds IntelliJ generated equals and hashCode to
DefaultPluginDescriptor, PluginDependency, and PluginClasspath.

adds equals/hashCode to some data classes

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/PluginState.java
pf4j/src/main/java/org/pf4j/PluginWrapper.java

There is no easy way how to distinguish FAILED and STOPPED/RESOLVED plugins.

Failed plugin state added. When plugin failed to start previous state was kept

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/PluginClassLoader.java
pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java

I've been working with Pf4j and Spring and have come across an issue when using hierarchical plugins and Spring. In my project, I have a plugin that provides an SSH server component to my application. I then have several other plugins that depend on this, that provide command implementations to the SSH server.
The command implementations depend on an Interface in the SSH server plugin. It is not an ExtensionPoint, it is simply an interface and the Spring components are created by the SpringPlugin's during the creation of the ApplicationContext.
When using this setup, spring initialization fails with the current 3.3.0-SNAPSHOT because Spring attempts to load the class of my interface using getResource (I assume it does this because of all the magical stuff Spring does). This only checks …

PluginClassLoader does not resolve classpath resources from plugin dependencies

---

pf4j/src/main/java/org/pf4j/BasePluginRepository.java
pf4j/src/test/java/org/pf4j/AbstractExtensionFinderTest.java

This prevents downcasting errors where files can have a negative time, causing TimSort to go haywire and throw an exception.

Sort files using last modified as long

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/PluginClassLoader.java
pf4j/src/main/java/org/pf4j/PluginWrapper.java

Hi. There is an error in logical condition. Class loading from optional dependency is always skipped because of OR logical condition.
Also I have made some methods protected instead of private to make them usable in descendants, and added fix for starting optional dependencies. Those changes are based on use-case of pf4j library in my project. Thanks!

Fix wrong logical condition (optional dependencies are always skipped)

---

pf4j/src/main/java/org/pf4j/DefaultPluginDescriptor.java
pf4j/src/test/java/org/pf4j/DefaultPluginDescriptorTest.java

Do not use Collections.emptyList() to create empty lists that should be writable,
otherwise an UnsupportedOperationException is thrown when you try to add something to that list.
This is especially annoying as it is not easy to fix in a subclass because of the asynchronous setter and getter of dependencies (Is that really a good idea?).

Make DefaultPluginDescriptor#addDependency usable

---

pf4j/src/main/java/org/pf4j/SingletonExtensionFactory.java
pf4j/src/test/java/org/pf4j/SingletonExtensionFactoryTest.java

Bucketed cache in `SingletonExtensionFactory` grouped by `ClassLoaders`
`SingletonExtensionFactory` caches extensions based on class names alone. When two extensions with same class name from two different plugins(essentially two different `ClassLoaders`) are loaded, only one of them gets instantiated and also gets served twice. This might functionally be incorrect since two extension from two different plugins should be treated different even when they share the same name.
[quickstart link](https://github.com/ajithalbus/pf4j/tree/singleton-issue-starter/singleton)
Here an additional plugin for `Greeting` called `hello-plugin-japanese`(which greets with "ohayō" which loosely translates to  "hello" in Japanese) is added along with existing `hello-plugin`. The `HelloPlugin` class exists in …

Bucketed caching in SingletonExtensionFactory

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/BasePluginRepository.java
pf4j/src/main/java/org/pf4j/DefaultPluginManager.java
pf4j/src/main/java/org/pf4j/DefaultPluginRepository.java
pf4j/src/main/java/org/pf4j/DevelopmentPluginRepository.java
pf4j/src/main/java/org/pf4j/JarPluginManager.java
pf4j/src/main/java/org/pf4j/JarPluginRepository.java
pf4j/src/main/java/org/pf4j/PluginManager.java
pf4j/src/main/java/org/pf4j/ZipPluginManager.java
pf4j/src/test/java/org/pf4j/DefaultPluginRepositoryTest.java
pf4j/src/test/java/org/pf4j/LoadPluginsFromMultipleRootsTest.java
pf4j/src/test/java/org/pf4j/LoadPluginsTest.java

* all constructors now support a varargs argument instead of a single Path
* property 'pf4j.pluginsDir' now supports a comma-separated list
* default directory for enabled / disabled files is the first plugin root
* PluginManager#getPluginsRoot() returns the first plugin root
Fixes #403
I tried to  keep the changes API-compatible. If binary compatibility is necessary, we could re-add the old One-Argument-Constructors.

Support multiple plugin root directories

---

pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/main/java/org/pf4j/PluginClassLoader.java
pf4j/src/main/java/org/pf4j/SecurePluginManagerWrapper.java
pf4j/src/test/java/org/pf4j/SecurePluginManagerWrapperTest.java

solves #353 
- extracted PluginWrapper creation into separate method `createPluginWrapper`
- added `SecurePluginManagerWrapper` for users who want to prevent plugins having full access to pluginManager which can be used like this:
```java
public class SecurePluginManager extends DefaultPluginManager  {
@Override
protected PluginWrapper createPluginWrapper(PluginDescriptor pluginDescriptor, Path pluginPath, ClassLoader pluginClassLoader) {
PluginWrapper pluginWrapper = new PluginWrapper(new SecurePluginManagerWrapper(this, pluginDescriptor.getPluginId()), pluginDescriptor, pluginPath, pluginClassLoader);
pluginWrapper.setPluginFactory(getPluginFactory());
return pluginWrapper;
}
}
```
- added tests for `SecurePluginManagerWrapper`
Open points:
- ~Test for `whichPlugin` fails because …

add wrapper to plugin manager

---

pf4j/pom.xml
pf4j/src/main/java-templates/org/pf4j/Pf4jInfo.java
pf4j/src/main/java-templates/org/pf4j/Pf4jVersion.java
pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
pf4j/src/test/java/org/pf4j/AbstractPluginManagerTest.java

solves #390
- added generated class Pf4jVersion to contain the current version
- added templating-maven-plugin to add project version into Pf4jVersion
- added UnitTest for version

do not rely on version from Manifest

---

maven-archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
pom.xml

Updating log4j library version to 2.15.0 to handle [**CVE-2021-44228**](http://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-44228) to patch remote code execution vulnerability in Apache log4j

Upgrade to Log4j version to 2.15.0

---

maven-archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
pom.xml

Updating Log4j version to 2.17.0 because of CVE-2021-45105 vulnerability.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

Update Log4j version to 2.17.0

---

maven-archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
pom.xml

Updating Log4j version to 2.17.1 because of CVE-2021-44832 vulnerability.
https://nvd.nist.gov/vuln/detail/CVE-2021-44832

Update Log4j to 2.17.1 to address CVE-2021-44832

---

README.md

Update README url to avoid SSL_ERROR_BAD_CERT_DOMAIN error when connecting to side
Currently, when you click on the link in the README, you get this very nice page (firefox):
This change fixes that by updating `http://www.pf4j.org` -> `http://pf4j.org`

Update README url

---

pf4j/src/main/java/org/pf4j/util/FileUtils.java
pf4j/src/test/java/org/pf4j/util/FileUtilsTest.java

When `ignoreComments=false` the `FileUtils.readLines(file.toPath(), false)` will read nothing.

Fix： Wrong judgment condition for `ignoreComments`.

---

pf4j/src/main/java/org/pf4j/processor/ExtensionAnnotationProcessor.java

Closes #550 
I tried this only with the legacy mechanism. Not 100% sure whether it works with JDK9 module mechanism, too - but I see no reason that it shouldn't.

Write empty extensions descriptor even if no extensions are found

---

pf4j/pom.xml
pf4j/src/main/java/module-info.java

Recently, I have noticed that the project <https://github.com/zafarkhaja/jsemver> has become active again and they have releases some new versions. See <https://github.com/zafarkhaja/jsemver/releases> for more.
This PR upgrades the dependency to [0.10.2(latest)](https://github.com/zafarkhaja/jsemver/releases/tag/v0.10.2).

Upgrade Java SemVer to 0.10.2

---

.github/workflows/build.yml

I have noticed that there are too many failure actions as sonar refuses to scan in JDK 11, please refer to <https://github.com/pf4j/pf4j/actions/runs/7700538547/job/20984594068>.
```bash
Warning:  The version of Java (11.0.22) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.371 s
[INFO] Finished at: 2024-01-25T04:16:40Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar (default-cli) on …
```

Fix the problem of unable doing sonar scanning in JDK 11

---

pf4j/pom.xml
pf4j/src/main/java/org/pf4j/AbstractExtensionFinder.java
pf4j/src/test/java/org/pf4j/AbstractExtensionFinderTest.java

Currently this method gets caught in a loop (target -> retention -> mustbedocumented -> target) if @Extension is not present
this fixes it

Fix StackOverFlow error on Kotlin classes without @Extension

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

These files are generated by executing command `mvn wrapper:wrapper -Dmaven=3.9.9`. We can replace command `mvn` with `./mvnw`, because it will automatically download Maven into development environment with specific version.
Maven to date has been very stable for users, is available on most systems or is easy to procure: but with many of the recent changes in Maven it will be easier for users to have a fully encapsulated build setup provided by the project. With the Maven Wrapper, this is very easy to do and it's a great idea and initial implementation borrowed from Gradle.
> https://maven.apache.org/wrapper/

Add Maven wrapper support

---

.gitignore

This PR add `bin/` into `.gitignore` file to exclude bin folder built by Eclipse or VSCode. See the output of `git status`:
```bash
❯ git status
HEAD detached at upstream/master
Untracked files:
(use "git add <file>..." to include in what will be committed)
demo/gradle/api/bin/
demo/gradle/app/bin/
demo/gradle/plugins/plugin1/bin/
demo/gradle/plugins/plugin2/bin/
demo/gradle/plugins/plugin3/bin/
nothing added to commit but untracked files present (use "git add" to track)
```

Exclude bin folder built by Eclipse or VSCode

---

.github/workflows/build.yml

This PR fixes the deprecate warnings from [GitHub Actions](https://github.com/pf4j/pf4j/actions/runs/12144934668).
See
- https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
- https://github.com/actions/runner-images/issues/10636
for more.

Fix the deprecation warnings from GitHub Actions
